### ISSUE TITLE
Can this plugin work on Maya2016?

### ISSUE THREAD

**Issue by liushengxin** [Ziriax/Maya2glTF#2]
Is there some test on Maya 2016 x64 ？

**Comment by Ziriax** [comment]
Currently I'm only testing it on Maya 2017 and 2018, but adding support for 2016 should be easy, I'll put it on my TODO list.

**Comment by liushengxin** [comment]
Thanks for reply, I 'll get to build it and have a try and report the result. 

Thanks for all your efforts ,

**Comment by Ziriax** [comment]
Thanks for your interest in this project!

You're going to be the first to try to build it, good luck :-) 

And please provide feedback if things go wrong, because that is to be expected, it's work in progress.

Please note that only static meshes are currently supported. We are currently working on fully exporting the PBR material from our GLSL shader, ported from the Khronos PBR shader (with some bug fixes).

In the coming weeks, more people will work on the exporter, so we hope to tackle blend-shape and skinning animation soon.

**Comment by Ziriax** [comment]
BTW: I'm adding Maya 2016 support right now, because we already did that for the old OGRE exporter. I'm not expecting problems, unless the old Maya API doesn't work well with the new C++ 17 standard we're using.

**Comment by Ziriax** [comment]
@liushengxin What version of Maya 2016 are you using? It seems 2016 SP6 and 2016 EXT2 SP2 are different installations for some strange reason...  See https://knowledge.autodesk.com/support/maya/troubleshooting/caas/sfdcarticles/sfdcarticles/Maya-2016-extension-2-installation.html

**Comment by Ziriax** [comment]
Works on 2016 EXT2 now, cannot find SDK for 2016 itself
