### ISSUE TITLE
Number of vertices

### ISSUE THREAD

**Issue by jpvaillancourt** [Ziriax/Maya2glTF#22]
I have a question for you. I have made a simple polySphere to export to learn a bit more about the glTF format.

I have 382 vertices into my scene, but when I use your exporter, the accessor has a count of 439. Even the accessor for the indices has a a maz of 438 (the biggest index).

I would like to know since it means there's a difference in the file size at the end.

**Comment by Ziriax** [comment]
glTF allows only a single vertex index buffer, as all elements of vertex must be combined into a single "structure".  By default Maya2glTF combines the position, normal, texture coordinates, colors and tangent elements (aka semantics, attributes)

For example, if you have a cube, then 24 vertices will be exported, because each vertex has 3 normals, one for each face. So even though you only see 8 corners, we still need to export 24 vertices.

If you would smooth the normals of the cube, then less vertices would be exported, but the UV unwrapping will still create different UV coordinates for many triangle vertices. Also the tangents that are generated are not always the same.

You can control what attribute you want to export with the `-mpa` flag (long name `meshPrimitiveAttributes`). For example, specifying `-mpa POSITION|NORMAL` in the `extra flags` of the exporter UI will only export positions and normals for each vertex. In the case of a smoothed cube, only 8 vertices will be exported then.
